# Generated by Django 2.1.7 on 2019-02-19 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('basic_salary', models.IntegerField()),
                ('house_rent', models.IntegerField()),
                ('medical_allowance', models.IntegerField()),
                ('lunch_bill', models.IntegerField()),
                ('transportation_allowance', models.IntegerField()),
                ('net_salary', models.IntegerField()),
            ],
        ),
    ]
