# Generated by Django 2.1.7 on 2019-02-15 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('basic_salary', models.IntegerField()),
                ('house_rent', models.IntegerField()),
                ('medical_allowance', models.IntegerField()),
                ('lunch_bill', models.IntegerField()),
                ('transportation_allowance', models.IntegerField()),
                ('net_salary', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_date', models.DateTimeField()),
                ('grade', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='salary.Grade')),
            ],
        ),
    ]
