# Generated by Django 2.1.7 on 2019-02-15 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_auto_20190215_1517'),
        ('salary', '0002_remove_salary_salary_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salary',
            name='grade',
        ),
        migrations.DeleteModel(
            name='Salary',
        ),
    ]
