# Generated by Django 2.1.5 on 2019-02-08 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=130)),
                ('father_name', models.CharField(max_length=130)),
                ('mother_name', models.CharField(max_length=130)),
                ('nid', models.IntegerField()),
                ('present_address', models.TextField(max_length=150)),
                ('permanent_address', models.TextField(max_length=150)),
                ('phone', models.IntegerField()),
                ('image', models.ImageField(blank=True, upload_to='employee/%Y/%m/%d')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
