# Generated by Django 2.1.7 on 2019-02-19 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeedepartment',
            name='department',
        ),
        migrations.RemoveField(
            model_name='employeedepartment',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='employeedesignation',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='employeedesignation',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='employeesection',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='employeesection',
            name='section',
        ),
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='employee.Department'),
        ),
        migrations.AddField(
            model_name='employee',
            name='designation',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='employee.Designation'),
        ),
        migrations.AddField(
            model_name='employee',
            name='section',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='employee.Section'),
        ),
        migrations.DeleteModel(
            name='EmployeeDepartment',
        ),
        migrations.DeleteModel(
            name='EmployeeDesignation',
        ),
        migrations.DeleteModel(
            name='EmployeeSection',
        ),
    ]
