# Generated by Django 2.1.7 on 2019-02-21 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20190219_2250'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='attendance_date')),
                ('attendance_status', models.CharField(choices=[('A', 'Absent'), ('P', 'Present'), ('L', 'Leave')], max_length=1)),
                ('employee', models.ForeignKey(db_column='emp_no', on_delete=django.db.models.deletion.CASCADE, to='employee.Employee')),
            ],
        ),
    ]
