# Generated by Django 2.1.7 on 2019-02-15 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20190214_1838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departmentanddesignation',
            name='department_id',
        ),
        migrations.RemoveField(
            model_name='departmentanddesignation',
            name='designation_id',
        ),
        migrations.RemoveField(
            model_name='departmentandsection',
            name='department_id',
        ),
        migrations.RemoveField(
            model_name='departmentandsection',
            name='section_id',
        ),
        migrations.RemoveField(
            model_name='sectionandteam',
            name='section_id',
        ),
        migrations.RemoveField(
            model_name='sectionandteam',
            name='team_id',
        ),
        migrations.AlterField(
            model_name='employee',
            name='designation',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='employee.Designation'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='section',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='employee.Section'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='team',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='employee.Team'),
        ),
        migrations.DeleteModel(
            name='DepartmentAndDesignation',
        ),
        migrations.DeleteModel(
            name='DepartmentAndSection',
        ),
        migrations.DeleteModel(
            name='SectionAndTeam',
        ),
    ]
