# Generated by Django 2.1.7 on 2019-02-14 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_auto_20190213_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='section',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.Section'),
        ),
    ]
