# Generated by Django 2.1.7 on 2019-02-15 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0002_remove_salary_salary_date'),
        ('employee', '0003_auto_20190215_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='salary',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='salary.Salary'),
        ),
    ]
