# Generated by Django 2.1.7 on 2019-02-14 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_auto_20190214_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='section',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='employee.Section'),
        ),
    ]
