# Generated by Django 2.1.7 on 2019-02-15 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_auto_20190215_1517'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='salary',
            new_name='grade',
        ),
    ]
